Next
ionic-team/angular-toolkit pull request #486
Opened 2023-03-23 16:45 UTC by mhartington

2023-03-23 16:52 UTC, liamdebeasi requested changes

2023-03-23 16:52 UTC, liamdebeasi commented on packages/schematics/page/route-utils/index.ts
> +      throw new Error('whoops');
Can we add a more descriptive error message here?

2023-03-23 16:52 UTC, liamdebeasi commented on packages/schematics/page/route-utils/index.ts
> +  throw new Error('Could not find your routes file. Use the skip-import ' + 'option to skip importing.');
Why do we do ` ' + '`?

2023-03-23 16:52 UTC, liamdebeasi commented on packages/schematics/page/route-utils/index.ts
> +        'More than one module matches. Use skip-import option to skip importing ' +
Why do we do ` ' + '`?

2023-03-23 18:24 UTC, mhartington commented
>Why do we do  ' + '?

🤷  Some of this code predates me maintaining angular-toolkit, but I think it's safe to remove.

2023-03-23 18:32 UTC, liamdebeasi submitted a review, later dismissed
Code looks good, but I added Sean to take a look too.

Only final thing is can we add a write-up for the PR as to what it does/why it's needed?

2023-03-27 20:28 UTC, mhartington commented
Rebased and cleaned up the commits so we have can have 3 separate commits that are clear and understood. This should not be squashed, but merged in the traditional way

2023-03-27 21:25 UTC, liamdebeasi approved these changes

2023-03-28 02:05 UTC, sean-perkins approved these changes

2023-03-28 13:39 UTC, merged